### ISSUE TITLE
oracle_user - trying to drop user

### ISSUE THREAD

**Issue by hc81** [oravirt/ansible-oracle#241] opened 2021-06-24 08:06 UTC
Hi,
Can help? Facing issue trying to drop user. Have passed in both schema and state as below.

    - name: drop
       oracle_user: oracle_sid={{ inst_name.stdout }} mode={{ oraclemode }} schema=app1 state=absent

Error:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: check_user_exists() missing 1 required positional argument: 'schema'
fatal: [RHEL001]: FAILED! => {"changed": false, "module_stderr": "Shared connection to rhel001 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/oracle/.ansible/tmp/ansible-tmp-1624521782.91-6332-148691965626973/AnsiballZ_oracle_user\", line 102, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/oracle/.ansible/tmp/ansible-tmp-1624521782.91-6332-148691965626973/AnsiballZ_oracle_user\", line 94, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/oracle/.ansible/tmp/ansible-tmp-1624521782.91-6332-148691965626973/AnsiballZ_oracle_user\", line 40, in invoke_module\r\n    runpy.run_module(mod_name='ansible.modules.oracle_user', init_globals=None, run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_oracle_user_payload_lv81c3uf/ansible_oracle_user_payload.zip/ansible/modules/oracle_user.py\", line 529, in <module>\r\n  File \"/tmp/ansible_oracle_user_payload_lv81c3uf/ansible_oracle_user_payload.zip/ansible/modules/oracle_user.py\", line 511, in main\r\nTypeError: check_user_exists() missing 1 required positional argument: 'schema'\r\n", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

thanks

**Comment by Rendanic** [comment] 2022-09-14 07:29
You did a test with the module `oracle_user` from https://github.com/oravirt/ansible-oracle-modules .
Thios is not the same as the role `oradb_manage_users` in ansible-oracle. I think that the problem is related to the reduced number of parameters while execution the module.

Closing, because this is not a bug in ansible-oracle. Maybe it is a bug in ansible-oracle-modules.

**Closed by Rendanic** 2022-09-14 07:29 UTC
Labels: question
